### ISSUE TITLE
Why Box<T> instead of plain T?

### ISSUE THREAD

**Issue by phil-opp** [m-labs/rust-managed#3]
Why does `Managed` required you to put the contents on the heap? Why doesn't it just look like this:

```rust
pub enum Managed<'a, T: 'a + ?Sized> {
    Borrowed(&'a mut T),
    #[cfg(/* Box available */)]
    Owned(T), // <--- no Box
}
```

**Comment by phil-opp** [comment]
Oh, I assume mainly for trait objects?

**Comment by whitequark** [comment]
Correct.

**Comment by phil-opp** [comment]
Ok thanks!

I was irritated by the EthernetInterface of smoltcp, which uses managed to store a generic device type: https://github.com/m-labs/smoltcp/blob/f64a99a4e6d744c3a6f3d9a54a0fb3f94e4b0ec8/src/iface/ethernet.rs#L28

Is this a mistake or am I still missing something?

**Comment by whitequark** [comment]
A mistake I think.
