### ISSUE TITLE
Can't build on latest nightly

### ISSUE THREAD

**Issue by BearzRobotics** [m-labs/rust-managed#5]
error[E0599]: no method named `rotate_left` found for type `[std::option::Option<(K, V)>]` in the current scope
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/managed-0.5.1/src/map.rs:161:38
    |
161 |                         pairs[idx..].rotate_left(rotate_by);
    |                                      ^^^^^^^^^^^

error[E0599]: no method named `rotate_left` found for type `[std::option::Option<(K, V)>]` in the current scope
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/managed-0.5.1/src/map.rs:187:38
    |
187 |                         pairs[idx..].rotate_left(1);
    |                                      ^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `managed`.

rustc version: nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.25.0-nightly (9fd7da904 2018-01-25)

**Comment by whitequark** [comment]
Nope. `rotate_left` is the [*new* name](https://doc.rust-lang.org/nightly/core/slice/trait.SliceExt.html#tymethod.rotate_left) for the method, so your nightly is too *old*. Try `rustc --version`, there's something wrong with your system.
